package com.cockyremax.db

import android.content.ContentValues
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import java.util.UUID

// ── User data class ────────────────────────────────────────────────────────────
data class User(
    val id: Int = 0,
    val userid: String = "",        // autogenerated random UUID-style string
    val username: String = "",
    val password: String = "",      // plain text as requested
    val picture: ByteArray? = null  // BLOB
)

// ── Database helper ────────────────────────────────────────────────────────────
class UserDatabase(context: Context) :
    SQLiteOpenHelper(context, DB_NAME, null, DB_VERSION) {

    companion object {
        private const val DB_NAME    = "cockyremax_users.db"
        private const val DB_VERSION = 1

        const val TABLE   = "users"
        const val COL_ID      = "id"        // INTEGER PRIMARY KEY AUTOINCREMENT
        const val COL_USERID  = "userid"    // TEXT — random UUID string, unique
        const val COL_USERNAME= "username"  // TEXT UNIQUE
        const val COL_PASSWORD= "password"  // TEXT (plain)
        const val COL_PICTURE = "picture"   // BLOB

        // Generates a userid that mixes a UUID with a random integer component.
        // Example: "usr_4f2a1b3c-7812-4e9d-a3f1-092847563011_48392"
        fun generateUserId(username: String): String {
            val uuid    = UUID.randomUUID().toString()
            val randNum = (10000..99999).random()
            return "usr_${uuid}_${randNum}"
        }
    }

    override fun onCreate(db: SQLiteDatabase) {
        db.execSQL("""
            CREATE TABLE $TABLE (
                $COL_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
                $COL_USERID   TEXT NOT NULL UNIQUE,
                $COL_USERNAME TEXT NOT NULL UNIQUE,
                $COL_PASSWORD TEXT NOT NULL,
                $COL_PICTURE  BLOB
            )
        """.trimIndent())
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        db.execSQL("DROP TABLE IF EXISTS $TABLE")
        onCreate(db)
    }

    // ── INSERT new user ────────────────────────────────────────────────────────
    // Returns the generated userid string on success, null on failure (e.g. duplicate username)
    fun insertUser(username: String, password: String, picture: ByteArray? = null): String? {
        return try {
            val userId = generateUserId(username)
            val cv = ContentValues().apply {
                put(COL_USERID,   userId)
                put(COL_USERNAME, username)
                put(COL_PASSWORD, password)
                if (picture != null) put(COL_PICTURE, picture) else putNull(COL_PICTURE)
            }
            val rowId = writableDatabase.insertOrThrow(TABLE, null, cv)
            if (rowId != -1L) userId else null
        } catch (e: Exception) {
            null  // duplicate username or other constraint violation
        }
    }

    // ── AUTHENTICATE ──────────────────────────────────────────────────────────
    // Returns the full User on success, null if credentials don't match
    fun authenticate(username: String, password: String): User? {
        val cursor = readableDatabase.query(
            TABLE,
            null,
            "$COL_USERNAME = ? AND $COL_PASSWORD = ?",
            arrayOf(username, password),
            null, null, null
        )
        return cursor.use {
            if (!it.moveToFirst()) return null
            User(
                id       = it.getInt(it.getColumnIndexOrThrow(COL_ID)),
                userid   = it.getString(it.getColumnIndexOrThrow(COL_USERID)),
                username = it.getString(it.getColumnIndexOrThrow(COL_USERNAME)),
                password = it.getString(it.getColumnIndexOrThrow(COL_PASSWORD)),
                picture  = it.getBlob(it.getColumnIndexOrThrow(COL_PICTURE))
            )
        }
    }

    // ── CHECK username taken ───────────────────────────────────────────────────
    fun usernameExists(username: String): Boolean {
        val cursor = readableDatabase.query(
            TABLE, arrayOf(COL_ID),
            "$COL_USERNAME = ?", arrayOf(username),
            null, null, null
        )
        return cursor.use { it.count > 0 }
    }

    // ── UPDATE picture for a user ──────────────────────────────────────────────
    fun updatePicture(userid: String, picture: ByteArray): Boolean {
        val cv = ContentValues().apply { put(COL_PICTURE, picture) }
        val rows = writableDatabase.update(TABLE, cv, "$COL_USERID = ?", arrayOf(userid))
        return rows > 0
    }
}
